### ISSUE TITLE
export csv

### ISSUE THREAD

**Issue by antoniosap** [yyl-20020115/RTLSDR-Scanner-Python3#1]
```
Traceback (most recent call last):
  File "/home/aldebaran/workspace-sdr-radio/RTLSDR-Scanner-Python3/rtlsdr_scanner/main_window.py", line 504, in __on_export_scan
    export_plot(fullName, dlg.GetFilterIndex(), self.spectrum)
  File "/home/aldebaran/workspace-sdr-radio/RTLSDR-Scanner-Python3/rtlsdr_scanner/file.py", line 414, in export_plot
    export_csv(handle, spectrum)
  File "/home/aldebaran/workspace-sdr-radio/RTLSDR-Scanner-Python3/rtlsdr_scanner/file.py", line 469, in export_csv
    handle.write(u"Time (UTC), Frequency (MHz),Level (dB/Hz)\n")
TypeError: a bytes-like object is required, not 'str'

```

**Comment by yyl-20020115** [comment]
Hi antoniosap,
Thanks for your kindly bug reporting.
Pls check update (git pull), and I hope I’ve fixed these bugs (including more bugs)
already. Pls let me know if any more.

Thanks!

Sincerely,
Yilin

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: antoniosap<mailto:notifications@github.com>
发送时间: 2020年4月13日 20:16
收件人: yyl-20020115/RTLSDR-Scanner-Python3<mailto:RTLSDR-Scanner-Python3@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [yyl-20020115/RTLSDR-Scanner-Python3] export csv (#1)


Traceback (most recent call last):

  File "/home/aldebaran/workspace-sdr-radio/RTLSDR-Scanner-Python3/rtlsdr_scanner/main_window.py", line 504, in __on_export_scan

    export_plot(fullName, dlg.GetFilterIndex(), self.spectrum)

  File "/home/aldebaran/workspace-sdr-radio/RTLSDR-Scanner-Python3/rtlsdr_scanner/file.py", line 414, in export_plot

    export_csv(handle, spectrum)

  File "/home/aldebaran/workspace-sdr-radio/RTLSDR-Scanner-Python3/rtlsdr_scanner/file.py", line 469, in export_csv

    handle.write(u"Time (UTC), Frequency (MHz),Level (dB/Hz)\n")

TypeError: a bytes-like object is required, not 'str'



―
